//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "contest_problems")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub contest_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub problem_id: i32,
    pub label: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::contests::Entity",
        from = "Column::ContestId",
        to = "super::contests::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Contests,
    #[sea_orm(
        belongs_to = "super::problems::Entity",
        from = "Column::ProblemId",
        to = "super::problems::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Problems,
}

impl Related<super::contests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contests.def()
    }
}

impl Related<super::problems::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Problems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
