//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "contests")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub title: String,
    #[sea_orm(unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub start_time: Option<DateTime>,
    pub end_time: Option<DateTime>,
    pub is_public: Option<bool>,
    pub author_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::contest_problems::Entity")]
    ContestProblems,
    #[sea_orm(has_many = "super::contest_registrations::Entity")]
    ContestRegistrations,
    #[sea_orm(has_many = "super::submissions::Entity")]
    Submissions,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::AuthorId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::contest_problems::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContestProblems.def()
    }
}

impl Related<super::contest_registrations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContestRegistrations.def()
    }
}

impl Related<super::submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submissions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::problems::Entity> for Entity {
    fn to() -> RelationDef {
        super::contest_problems::Relation::Problems.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::contest_problems::Relation::Contests.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
