//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::contest_problems::Entity as ContestProblems;
pub use super::contest_registrations::Entity as ContestRegistrations;
pub use super::contests::Entity as Contests;
pub use super::problems::Entity as Problems;
pub use super::submissions::Entity as Submissions;
pub use super::testcases::Entity as Testcases;
pub use super::users::Entity as Users;
