//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "problems")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    #[sea_orm(unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub statement: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub input_spec: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub output_spec: Option<String>,
    pub sample_inputs: Option<Json>,
    pub time_limit: i16,
    pub memory_limit: i16,
    pub difficulty: Option<String>,
    pub is_public: bool,
    pub created_at: DateTime,
    pub author_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::contest_problems::Entity")]
    ContestProblems,
    #[sea_orm(has_many = "super::submissions::Entity")]
    Submissions,
    #[sea_orm(has_many = "super::testcases::Entity")]
    Testcases,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::AuthorId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::contest_problems::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContestProblems.def()
    }
}

impl Related<super::submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submissions.def()
    }
}

impl Related<super::testcases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Testcases.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::contests::Entity> for Entity {
    fn to() -> RelationDef {
        super::contest_problems::Relation::Contests.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::contest_problems::Relation::Problems.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
