//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "submissions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub problem_id: i32,
    pub language: String,
    #[sea_orm(column_type = "Text")]
    pub code: String,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub verdict: Option<String>,
    pub time: Option<i16>,
    pub memory: Option<i16>,
    pub submitted_at: DateTime,
    pub contest_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::contests::Entity",
        from = "Column::ContestId",
        to = "super::contests::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Contests,
    #[sea_orm(
        belongs_to = "super::problems::Entity",
        from = "Column::ProblemId",
        to = "super::problems::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Problems,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::contests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contests.def()
    }
}

impl Related<super::problems::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Problems.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
