//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "testcases")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub problem_id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub input: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub output: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::problems::Entity",
        from = "Column::ProblemId",
        to = "super::problems::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Problems,
}

impl Related<super::problems::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Problems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
