//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(unique)]
    pub username: String,
    pub password: String,
    pub rating: i16,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::contest_registrations::Entity")]
    ContestRegistrations,
    #[sea_orm(has_many = "super::contests::Entity")]
    Contests,
    #[sea_orm(has_many = "super::problems::Entity")]
    Problems,
    #[sea_orm(has_many = "super::submissions::Entity")]
    Submissions,
}

impl Related<super::contest_registrations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContestRegistrations.def()
    }
}

impl Related<super::contests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Contests.def()
    }
}

impl Related<super::problems::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Problems.def()
    }
}

impl Related<super::submissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submissions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
