[package]
name = "api_server"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "migration"]

[dependencies]
anyhow = "1.0.102"
async-stream = "0.3.6"
axum = { version = "0.8.8", features = ["macros", "ws"] }
axum-extra = { version = "0.12.5", features = ["typed-header"] }
bcrypt = "0.19.0"
chrono = "0.4.44"
dotenvy = "0.15.7"
futures-util = "0.3.32"
jsonwebtoken = { version = "10.3.0", features = ["rust_crypto"] }
lapin = { version = "4.3.0", features = ["rustls--ring"]}
rustls = { version = "0.23.37", features = ["ring"] }
sea-orm = { version = "2.0.0-rc.37", features = ["runtime-tokio-rustls", "sqlx-postgres"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = { version = "1.50.0", features = ["full"] }
tokio-stream = { version = "0.1.18", features = ["sync"] }
tower = "0.5.3"
tower-cookies = "0.11.0"
tower-http = { version = "0.6.8", features = ["full"] }
